# Generated by Django 2.2.12 on 2020-05-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ultrasonic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultrasonic',
            name='value',
        ),
        migrations.AddField(
            model_name='ultrasonic',
            name='area',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ultrasonic',
            name='distance',
            field=models.IntegerField(default=0, verbose_name='distance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ultrasonic',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='lat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ultrasonic',
            name='lng',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='lng'),
            preserve_default=False,
        ),
    ]
